name: CoreV6
main: TheNote\core\Main
version: 6.3.1_STABLE
api:
  - 4.20.1
author: TheNote/Rudolf2000/note3crafter
authors:
  - TheNote/Rudolf2000 #Inhaber der Core
  - tim03we #BanSystem usw
  - xxflow #Heiraten,Payall
  - Aneoxic #Grundgerüst
  - FleekRush #Booster
  - JackMD #Discord
  - LookItsAku #Hilfe
  - Philip #Für Hilfe
  - galaxytwenty #Hilfe bei den Blöcken
  - Hagnbrain #homesystem
  - EnderDirt #füraltecodes
  - Crasher508 #Fixxer
  - MDevPmmP #GroupSystem/EconomySystem
  - jojoe77777 #FormAPI
  - muqsit #InvMenü
  - TheBalkanDev #ecinvsee, invsee
  - GamerMJay #hilfe
description: Core v6.3.1 STABLE
extensions:
  - sqlite3
permissions:
  core.command.adventure:
    description: "Setze deinen Spielermodus zu Abendteuer"
    default: op
  core.command.adventure.other:
    description: "Setze einen anderen Spieler den Spielermodus zu Abendteuer"
    default: op
  core.command.adminitems:
    description: "Sei der King und benutze die Wunderwaffen"
    default: op
  core.command.admintitems.superbow:
    description: "gebe dir den Superbow"
    default: op
  core.command.admintitems.explosivbow:
    description: "gebe dir den Explosivbow"
    default: op
  core.command.admintitems.explosivegg:
    description: "gebe dir den Explosiveg"
    default: op
  core.command.afk.bypass:
    description: "Werde nicht automatich gekickt"
    default: op
  core.command.animation:
    description: "Teste verschiednene Animationen aus"
    default: op
  core.command.back:
    description: "TP dich zum letzten Punkt zurück"
    default: op
  core.command.ban:
    description: "Banne einen anderen Spieler"
    default: op
  core.command.banlist:
    description: "Siehe die Banlist"
    default: op
  core.command.burn:
    description: "Zünde einen Spieler an"
    default: op
  core.command.chatclear:
    description: "Lösche den Chat"
    default: op
  core.command.clear:
    description: "Cleare dein Inventar"
    default: op
  core.command.clear.other:
    description: "Cleare einem anderen Spieler das Inventar"
    default: op
  core.command.clearlagg:
    description: "Lösche alle Items & Blöcke die auf dem Boden Liegen"
    default: op
  core.command.craft:
    description: "Nutze die Werkbank als Command"
    default: op
  core.command.creativ:
    description: "Setze deinen Spielmodus zu Kreativ"
    default: op
  core.command.creativ.other:
    description: "Setze einem anderen Spieler den Spielmodus zu Kreativ"
    default: op
  core.command.datenbank:
    description: "Siehe in die DatenBank"
    default: op
  core.command.day:
    description: "Setze die Zeit auf Tag"
    default: op
  core.command.delwarp:
    description: "Lösche ein Warp"
    default: op
  core.command.enderchest:
    description: "Nutze deine Enderchest jederzeit"
    default: op
  core.command.enderinvsee:
    description: "Siehe in die Enderchest eines anderen Spielers"
    default: op
  core.command.fake:
    description: "Mache ein Fake leave/join"
    default: op
  core.command.feed:
    description: "Fress dich voll"
    default: op
  core.command.feed.other:
    description: "Füttere einen anderen Spieler"
    default: op
  core.command.fly:
    description: "Redbull verleiht dir die Macht zu fliegen!"
    default: op
  core.command.fly.other:
    description: "Redbull verleiht einem anderen die Macht zu fliegen!"
    default: op
  core.command.givecoins:
    description: "Gebe dir Coins"
    default: op
  core.command.givemoney:
    description: "Gebe dir Geld"
    default: op
  core.command.group:
    description: "Stelle deine Gruppe ein"
    default: op
  core.command.head:
    description: "Gebe dir dein Kopf"
    default: op
  core.command.heal:
    description: "Der lauch ist stark in dir und das heilt dich!"
    default: op
  core.command.heal.other:
    description: "Heile einen anderen Spieler!"
    default: op
  core.command.id:
      description: "Siehe die ID des Gegenstands."
      default: op
  core.command.invsee:
    description: "Siehe das Inventar eines anderen Spielers."
    default: op
  core.command.invsee.use:
    description: "Bearbeite das Inventar eines anderen Spielers."
    default: op
  core.command.kick:
    description: "Kicke einen Spieler vom Server"
    default: op
  core.command.kickall:
    description: "Kick alle weg und sei allein!"
    default: op
  core.command.nick:
    description: "Nicke dich und das bitte gesittet"
    default: op
  core.command.night:
    description: "Komm auf die dunkle Seite."
    default: op
  core.command.nightvision:
    description: "Obwohl es Nacht ist ist es Tag!"
    default: op
  core.command.nodm.bypass:
    description: "Bypass für MSGs zu schreiben"
    default: op
  core.command.nuke:
    desctiption: "Jage ein dickes Loch in den Boden!"
    default: op
  core.command.nuke.other:
    desctiption: "Nuke einen anderen Spieler!"
    default: op
  core.command.paycoins:
    description: "Zahle einen Spieler Coins"
    default: op
  core.command.position:
    description: "Schaue deine Position"
    default: op
  core.command.rename:
    description: "Nenne deinen Stein Horst"
    default: op
  core.command.repair:
    description: "Nutze dein Item unendlich Lang"
    default: op
  core.command.restart:
    description: "Restarte deinen Server"
    default: op
  core.command.seeperms:
    description: "Siehe die Perms eines Plugins"
    default: op
  core.command.servermute:
    description: "Stelle den Chat für Alle Stumm"
    default: op
  core.command.setmoney:
    description: "Setze den Geldstand eines Spielers"
    default: op
  core.command.setwarp:
    description: "Setze ein Warp"
    default: op
  core.command.sign:
    description: "Signiere dein Stein"
    default: op
  core.command.size:
    description: "Verändere deine Größe"
    default: op
  core.command.spectator:
    description: "Setze deinen Spielmodus zu Zuschauer"
    default: op
  core.command.spectator.other:
    description: "Setze einen anderem den Spielmodus zu Zuschauer"
    default: op
  core.command.sudo:
    description: "Führe eine Nachrricht/Command über ein anderen Spieler aus"
    default: op
  core.command.supervanish:
    description: "Sei unsichtbar für alle!"
    default: op
  core.command.survival:
    description: "Setze deinen Spielmodus zu Survival"
    default: op
  core.command.survival.other:
    description: "Setze einem anderem Spielmodus zu Survival"
    default: op
  core.command.takemoney:
    description: "Nehme das Held eines anderen Spielers"
    default: op
  core.command.tpall:
    description: "Teleportiere alle Spieler zu dir"
    default: op
  core.command.tree:
    description: "Tuh was gutes für die Umwelt und Pflanze ein Baum!"
    default: op
  core.command.unban:
    description: "Entbanne einen Spieler"
    default: op
  core.command.userdata:
    description: "Siehe die Userdaten eines Spieleres ein"
    default: op
  core.command.vanish:
    description: "Versteckt dich ohne Items in der Hand"
    default: op
  core.command.world:
    description: "Teleportiere dich zwichen welten"
    default: op
  core.command.godmode:
    description: "Werde unsterblich!"
    default: op
  core.command.music:
    description: "Spiele Musik"
    default: op
  core.command.sethub:
    description: "Setze den Hub"
    default: op
  core.command.milk:
    description: "Entferne deine Effekte"
    default: op
  core.economy.shop.create:
    default: op
  core.economy.sell.create:
    default: op
  core.economy.shop.buy:
    default: op
  core.economy.sell.sell:
    default: op
  core.economy.shop.remove:
    default: op
  core.economy.sell.remove:
    default: op
  core.events.bucketfill:
    default: op
  core.events.bucketempty:
    default: op
  core.events.drop:
    default: op
  core.events.blockplace:
    default: op
  core.events.blockbreak:
    default: op
  core.events.chat:
    default: op
  core.events.spawnbypass:
    default: op
  core.lift.admin.remove:
    default: op
  core.lift.admin.create:
    default: op
  core.lift.admin.interact:
    default: op
  core.lift.admin.use:
    default: op
  core.event.colorchat:
    default: op
  core.economy.chestshop.admin:
    default: op
  core.events.lightningrod:
    default: op
  core.command.top:
    default: op
    description: "Teleportiert dich zum höchsten Block"
  core.command.compass:
    default: op
    description: "Zeige wo du hinschauts"
  core.command.speed:
    default: op
    description: "Gebe deine Geschwindigkeit an"
  core.command.extinguish:
    default: op
    description: "Lösche dein Brand"
  core.command.extinguish.other:
    default: op
  core.command.realname:
    default: op
    description: "zeige den Spielernamen von einem Genickten name"
  core.command.near:
    default: op
    description: "Zeige Spieler in deiner nähe"
  core.command.jump:
    default: op
    description: "tp dich zum angesehenen block"
  core.event.itemframe:
    default: op
  core.event.flint:
    default: op
  core.event.doors:
    default: op